### PR TITLE
add @tloudon's key

### PR DESCRIPTION
**Pull request by tloudon**
Hey @jc00ke!

Sorry I'm not quite following how this should work.  I've generated a gpg key and uploaded it to a keyserver.  All I need to do now is add it to the .sops.yaml?  I'm not sure what the syntax is supposed to be here and I didn't see an example on the sops page w/ multiple pgp keys.  Does this look right?

Thanks!

### CODE REVIEW

**Comment by jc00ke** [comment]
@tloudon I think I have to manually add your key, which I can do tonight.

**Comment by jc00ke** [comment]
Addressed by f7d1332

@tloudon Yeah, this was a weird workflow. Pull down `master` and see if you can `sops twitter.yaml` to open the file. Lemme know and I'll update the `README` with more instructions. I think I'll submit an issue to mozilla/sops too.

**Comment by tloudon** [comment]
@jc00ke thanks!

It's not working for me.  I tried downloading your public key also--kind of grasping at straws here.

> sops twitter.yaml
> Failed to get the data key required to decrypt the SOPS file.
> 
> Group 0: FAILED
>   820A5BE1B38C55E51C2CA163FA065807F03AB48B: FAILED
>     - | could not decrypt data key with PGP key:
>       | golang.org/x/crypto/openpgp error: Could not load secring:
>       | open /Users/tloudon/.gnupg/secring.gpg: no such file or
>       | directory; GPG binary error: exit status 2
> 
>   41F783CAB350DE53C49A05FE8554D06FD5DA9BDD: FAILED
>     - | could not decrypt data key with PGP key:
>       | golang.org/x/crypto/openpgp error: Could not load secring:
>       | open /Users/tloudon/.gnupg/secring.gpg: no such file or
>       | directory; GPG binary error: exit status 2
> 
> Recovery failed because no master key was able to decrypt the file. In
> order for SOPS to recover the file, at least one key has to be successful,
> but none were.

I think this might only work if we have a shared secret gpg key-- if so, we could just create a new gpg key and share the secret key in person at meetups.  Then there would only be one thing to share, but changing that would be a hurdle.

**Comment by jc00ke** [comment]
No shared key needed. That's what `sops` solves. Looks like `sops` isn't finding your GPG key file. What version of `sops` and `gpg` do you have? Could something in https://github.com/mozilla/sops/issues/189 be applicable to your setup?

**Comment by tloudon** [comment]
Ahh.  I have
gpg (GnuPG) 2.2.7
sops 3.0.3 (latest)

So re mozilla/sops#189, I have pubring.kbx format.  There's a reference to mozilla/sops/issues/#304 and 
```
GPG_TTY=$(tty)
export GPG_TTY 
```
resolves the issue.
(see https://github.com/mozilla/sops/issues/304#issuecomment-377195341)

So I think we are cool!  Thanks!

WRT the README, are you on mac or linux?  I installed sops and gpg2 through homebrew.  The workflow would be:
1. Install sops and if necessary gpg2 + create a 4096 RSA key + upload to keyserver
2. update your env vars
3. add gpg fingerprint to fingerprints.txt + create a PR?

**Comment by jc00ke** [comment]
I run Linux, but your steps sound legit. Care to whip up a PR for those additions?

As a note, I had to:

```
> sops -r --add-pgp 4242somepgpkey twitter.enc.yaml
> mv twitter.enc.yaml twitter.yaml
```

otherwise the `sops` command would just kick output to `STDOUT`. This seems like the wrong behavior, so I'll create an issue for it.

**Comment by jc00ke** [comment]
mozilla/sops#349

**Comment by tloudon** [comment]
@jc00ke yes, i will create a PR on the README.  THANKS!

**Pull request closed without merging**
